### ISSUE TITLE
RiferimentoComune/Ente

### ISSUE THREAD

**Issue by ggentili** [AgID/ssu-ws#1]
riguardo...

<xs:element name="RiferimentoComune" type="msgtype:CodiceIstatComuneType"/>

...forse sarebbe meglio generalizzare. Cosa succede se la cosa compete ad Unione di Comuni o altra forma associata? Si potrebbe usare il nome "RiferimentoEnte" e il relativo codice IndicePA (che tutti gli enti pubblici hanno).

**Comment by giacomo83** [comment]
fixe by #13
