### ISSUE TITLE
Riferimento territoriale

### ISSUE THREAD

**Issue by lucagargiulo** [AgID/ssu-ws#12]
Problema: il riferimento territoriale usa la codifica ISTAT dei Comuni

E’ importante che tutti i componenti del SSU usino lo stesso set di metadati (stessa versione e stesso livello di specializzazione delle informazioni).
Per questo motivo il riferimento territoriale viene stabilito dal front-office in funzione del Procedimento e dello Sportello Unico che deve prenderlo in carico e poi viene passato invariato a back-office ed enti terzi.
Serve ad identificare nel Registro SSU il set di metadati pertinenti ad un procedimento erogato dallo Sportello Unico che deve erogare il servizio richiesto, in modo che possano essere recepite eventuali personalizzazioni definite localmente, nell’ambito territoriale applicabile allo specifico Sportello Unico.
Per come funziona il SSU tutti i componenti accedono ad un Registro SSU di riferimento (può essere locale, ma anche un Registro condiviso a livello Regionale, è solo una questione di HA e prestazioni, perché il contenuto viene mantenuto sincronizzato su tutti i Registri).
Un’Api del Registro consentirà di interrogare il proprio Registro e recuperare il riferimento territoriale in funzione del Procedimento e dello sportello unico selezionato dal Presentatore.
Il riferimento territoriale consentirà di selezionare la sezione del Registro SSU corretta.
La personalizzazione avviene a livello del singolo procedimento che ne ha necessità (magari su centinaia di procedimenti solo per uno o due è stata fatta una personalizzazione locale).
Come regola generale un procedimento può essere personalizzato solo fintanto che la personalizzazione impatta solo sugli enti terzi del territorio nel cui ambito opera lo sportello unico.
Se impatta su enti che operano anche per altri sportelli unici di altri ambiti territoriali può essere accettata solo se condivisa anche dagli altri ambiti territoriali.
Quindi ad es. i moduli dei VdF devono essere nazionali, quelli delle Aziende Sanitari devono essere Regionali, quelli degli endo-procedimenti dei comuni possono essere personalizzati a livello di ambito territoriale coperto dallo Sportello Unico.
Per uno stesso procedimento posso avere alcuni metadati modificati a livello regionale ed altri a livello di Sportello Unico, al provvedimento verrà assegnato un riferimento territoriale di Sportello Unico (quello più specifico).
Va anche tenuto conto che non tutti gli Sportelli Unici sono localizzati in un Comune: in Regione FVG esistono (almeno per ora) le Unioni Territoriali Intercomunali (UTI), i raggruppamenti di Comuni e le Comunità Montane che possono essere sede di SUAP, alcuni sportelli unici possono essere regionali (Regione o Agenzia Regionale).
Potrei peraltro avere più sportelli unici che condividono lo stesso set di personalizzazioni per un certo procedimento pur insistendo su territori diversi.

Possibili soluzioni

Il codice IPA potrebbe essere adatto ad identificare un qualsiasi ente e quindi uno sportello unico
<xs:simpleType name="CodiceIpaType">
    <xs:annotation>
      <xs:documentation>
         pattern da definire se possibile
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string"/>
</xs:simpleType>

In alternativa si potrebbe definire una codifica gestita appositamente per identificare l’ambito di personalizzazione di una porzione del Registro, magari condivisa da più sportelli unici.
Considerato che la territorialità è legata anche al territorio degli enti terzi coinvolti nel procedimento e non solo alla localizzazione dello sportello unico forse ha più senso la seconda soluzione.
La verifica che le personalizzazioni siano fatte in modo “territorialmente” valido non è così banale da fare in automatico.
Manterrei però il codice IPA per altri motivi.

**Comment by giacomo83** [comment]
fixed by #13
