### ISSUE TITLE
Elenco e codifica procedimenti

### ISSUE THREAD

**Issue by ggentili** [AgID/ssu-ws#2]
riguardo...

<xs:element name="IDProcedimento" type="msgtype:IDProcedimentoType"/>
(..)
<xs:simpleType name="IDProcedimentoType">
        <xs:restriction base="xs:nonNegativeInteger"/>
</xs:simpleType>

...come si pensa di codificare i procedimenti (e dove saranno disponibili gli elenchi di procedimenti/codici dei singoli enti)? forse il tipo IDProcedimentoType potrebbe avere qualche informazione in più (ad esempio un denominazione procedimento, regime amministrativo, ecc).
...come si pensa di collegare procedimenti, endo-procedimenti e istanze/moduli?

**Comment by giacomo83** [comment]
La banca dati dei procedimenti, cosi come tutti i metadati necessari per consentire la trasmissione delle istanze e delle informazioni di processo intorno ad esse tra le componenti logiche del sistema sono mantenuti nella componente di Registro(Catalogo SSU).
