### ISSUE TITLE
Identificativo dell'istanza

### ISSUE THREAD

**Issue by lucagargiulo** [AgID/ssu-ws#6]
Problema: tipo di dato troppo specifico

Se ho capito bene è l’id che mantiene la correlazione fra tutti i messaggi riferite alla stessa domanda unica. Viene definita come intero non negativo:
    <xs:simpleType name="IDIstanzaType">
        <xs:restriction base="xs:nonNegativeInteger"/>
    </xs:simpleType>
L’id istanza deve identificare univocamente un’istanza del procedimento che nasce dalla domanda unica di un soggetto, quindi dovrà essere univoco all’interno del dominio amministrativo di un Ente (o meglio di una AOO di un ente).
Per il sistema di trasporto risulta indifferente il tipo di dato ed eventuali vincoli di formato.
Possibile soluzione
Si propone di usare un tipo di dati stringa che consente di serializzare qualsiasi tipo di dato, per consentire implementazioni diverse, ad es basate su Guid o altri schemi che assicurino comunque il rispetto del requisito di univocità.
<xs:simpleType name="IDIstanzaType">
   <xs:annotation>
	   <xs:documentation>identifica in modo univoco in un ente un'istanza di procedimento
   </xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:string" />
    </xs:simpleType>

**Comment by giacomo83** [comment]
fixed by #14
