### ISSUE TITLE
Identificativo del procedimento

### ISSUE THREAD

**Issue by lucagargiulo** [AgID/ssu-ws#7]
Problema: tipo di dato troppo specifico

Identifica univocamente un procedimento all’interno del dominio amministrativo di un Ente (o meglio di una AOO di un ente). Viene definito come intero non negativo.

Possibile soluzione

Come per l’di istanza e per motivazioni analoghe si propone di usare un tipo string come tipo base.
<xs:simpleType name="IDProcedimentoType">
   <xs:annotation>
	   <xs:documentation>identifica in modo univoco in un ente un tipo di procedimento
   </xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:string" />
    </xs:simpleType>

**Comment by giacomo83** [comment]
L'identificativo del procedimento è unico per l'intero sistema, in quanto la banca dati dei procedimenti è censita nella componente di Registro (Catalogo SSU), ne consegue che utilizzare un numero (tipicamente un progressivo) come identificativo è da ritenersi una soluzione valida e sufficiente.
Il Gdl concorda nel mantere il type attuale.
